# practice dataset
# ------------------------------------------------------------------

# using read_excel() load the student dataset

In [1]:
import pandas as pd
df=pd.read_excel('student.xlsx')

In [2]:
df=df.drop(columns=['Unnamed: 0'])

# using df.columns understand the dataset features(columns)

In [3]:
df.columns

Index(['id', 'gen', 'age', 'location', 'score', 'state'], dtype='object')

# using df.info() understand the column information

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        24 non-null     int64
 1   gen       22 non-null     object
 2   age       20 non-null     float64
 3   location  12 non-null     object
 4   score     24 non-null     int64
 5   state     12 non-null     object
dtypes: float64(1), int64(2), object(3)
memory usage: 1.3+ KB

# using head() get top 6 students and understand the data

In [5]:
df.head(6)

    id     gen   age   location  score          state
0  101  female  22.0  hyderabad     55  andra pradesh
1  102  female  23.0        NaN     77            NaN
2  101  female  22.0  hyderabad     55  andra pradesh
3  104  female  21.0        NaN     99            NaN
4  105    MALE  23.0  Bengaluru     13      karnataka
5  106  female  21.0        NaN     32            NaN

# check for duplicates using duplicated()

In [6]:
df.duplicated().any()

np.True_

In [7]:
df

     id     gen   age   location  score          state
0   101  female  22.0  hyderabad     55  andra pradesh
1   102  female  23.0        NaN     77            NaN
2   101  female  22.0  hyderabad     55  andra pradesh
3   104  female  21.0        NaN     99            NaN
4   105    MALE  23.0  Bengaluru     13      karnataka
5   106  female  21.0        NaN     32            NaN
6   107    MALE  23.0        NaN     13            NaN
7   108  female  23.0        NaN     13            NaN
8   109     NaN  22.0        NaN     92            NaN
9   110    MALE  23.0        NaN     10            NaN
10  111  female   NaN      kochi     13         kerala
11  112  female  21.0     mumbai     13    maharashtra
12  113  female  21.0        NaN     65            NaN
13  114     NaN  21.0  Bengaluru     13      karnataka
14  115    MALE  23.0        NaN     92            NaN
15  116    MALE   NaN        NaN     77            NaN
16  117    MALE  23.0  hyderabad     55  andra pradesh
17  118  female  22.0    chennai     36     tamil nadu
18  119  female   NaN      kochi     46         kerala
19  120  female  23.0      kochi     46         kerala
20  103  female   NaN     mumbai     13    maharashtra
21  101  female  22.0  hyderabad     55  andra pradesh
22  104  female  21.0        NaN     99            NaN
23  104  female  21.0        NaN     99            NaN

# remove the duplicates using drop_duplicates()

In [8]:
df=df.drop_duplicates()

In [9]:
df

     id     gen   age   location  score          state
0   101  female  22.0  hyderabad     55  andra pradesh
1   102  female  23.0        NaN     77            NaN
3   104  female  21.0        NaN     99            NaN
4   105    MALE  23.0  Bengaluru     13      karnataka
5   106  female  21.0        NaN     32            NaN
6   107    MALE  23.0        NaN     13            NaN
7   108  female  23.0        NaN     13            NaN
8   109     NaN  22.0        NaN     92            NaN
9   110    MALE  23.0        NaN     10            NaN
10  111  female   NaN      kochi     13         kerala
11  112  female  21.0     mumbai     13    maharashtra
12  113  female  21.0        NaN     65            NaN
13  114     NaN  21.0  Bengaluru     13      karnataka
14  115    MALE  23.0        NaN     92            NaN
15  116    MALE   NaN        NaN     77            NaN
16  117    MALE  23.0  hyderabad     55  andra pradesh
17  118  female  22.0    chennai     36     tamil nadu
18  119  female   NaN      kochi     46         kerala
19  120  female  23.0      kochi     46         kerala
20  103  female   NaN     mumbai     13    maharashtra

# check the information of columns usin info()

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 20
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        20 non-null     int64
 1   gen       18 non-null     object
 2   age       16 non-null     float64
 3   location  10 non-null     object
 4   score     20 non-null     int64
 5   state     10 non-null     object
dtypes: float64(1), int64(2), object(3)
memory usage: 1.1+ KB

# display the df

In [11]:
df

     id     gen   age   location  score          state
0   101  female  22.0  hyderabad     55  andra pradesh
1   102  female  23.0        NaN     77            NaN
3   104  female  21.0        NaN     99            NaN
4   105    MALE  23.0  Bengaluru     13      karnataka
5   106  female  21.0        NaN     32            NaN
6   107    MALE  23.0        NaN     13            NaN
7   108  female  23.0        NaN     13            NaN
8   109     NaN  22.0        NaN     92            NaN
9   110    MALE  23.0        NaN     10            NaN
10  111  female   NaN      kochi     13         kerala
11  112  female  21.0     mumbai     13    maharashtra
12  113  female  21.0        NaN     65            NaN
13  114     NaN  21.0  Bengaluru     13      karnataka
14  115    MALE  23.0        NaN     92            NaN
15  116    MALE   NaN        NaN     77            NaN
16  117    MALE  23.0  hyderabad     55  andra pradesh
17  118  female  22.0    chennai     36     tamil nadu
18  119  female   NaN      kochi     46         kerala
19  120  female  23.0      kochi     46         kerala
20  103  female   NaN     mumbai     13    maharashtra

# sort the data according to student id (asc order using sort_values())

In [12]:
df=df.sort_values(by='id',ascending=True)

In [13]:
df

     id     gen   age   location  score          state
0   101  female  22.0  hyderabad     55  andra pradesh
1   102  female  23.0        NaN     77            NaN
20  103  female   NaN     mumbai     13    maharashtra
3   104  female  21.0        NaN     99            NaN
4   105    MALE  23.0  Bengaluru     13      karnataka
5   106  female  21.0        NaN     32            NaN
6   107    MALE  23.0        NaN     13            NaN
7   108  female  23.0        NaN     13            NaN
8   109     NaN  22.0        NaN     92            NaN
9   110    MALE  23.0        NaN     10            NaN
10  111  female   NaN      kochi     13         kerala
11  112  female  21.0     mumbai     13    maharashtra
12  113  female  21.0        NaN     65            NaN
13  114     NaN  21.0  Bengaluru     13      karnataka
14  115    MALE  23.0        NaN     92            NaN
15  116    MALE   NaN        NaN     77            NaN
16  117    MALE  23.0  hyderabad     55  andra pradesh
17  118  female  22.0    chennai     36     tamil nadu
18  119  female   NaN      kochi     46         kerala
19  120  female  23.0      kochi     46         kerala

# reset the index using reset_index()

In [14]:
df=df.sort_values(by='id',ascending=True).reset_index(drop=True)

# change the gen col_name to gender using rename()

In [15]:
df=df.rename(columns={'gen':'gender'})

In [16]:
df

     id  gender   age   location  score          state
0   101  female  22.0  hyderabad     55  andra pradesh
1   102  female  23.0        NaN     77            NaN
2   103  female   NaN     mumbai     13    maharashtra
3   104  female  21.0        NaN     99            NaN
4   105    MALE  23.0  Bengaluru     13      karnataka
5   106  female  21.0        NaN     32            NaN
6   107    MALE  23.0        NaN     13            NaN
7   108  female  23.0        NaN     13            NaN
8   109     NaN  22.0        NaN     92            NaN
9   110    MALE  23.0        NaN     10            NaN
10  111  female   NaN      kochi     13         kerala
11  112  female  21.0     mumbai     13    maharashtra
12  113  female  21.0        NaN     65            NaN
13  114     NaN  21.0  Bengaluru     13      karnataka
14  115    MALE  23.0        NaN     92            NaN
15  116    MALE   NaN        NaN     77            NaN
16  117    MALE  23.0  hyderabad     55  andra pradesh
17  118  female  22.0    chennai     36     tamil nadu
18  119  female   NaN      kochi     46         kerala
19  120  female  23.0      kochi     46         kerala

# get unique values of gender column using unique()

In [17]:
df['gender'].unique()

array(['female', 'MALE', nan], dtype=object)

# convert gender values to title case and repalce the incomplete values using (str.title() and replace() )

In [18]:
df['gender']=df['gender'].str.title()

In [19]:
df

     id  gender   age   location  score          state
0   101  Female  22.0  hyderabad     55  andra pradesh
1   102  Female  23.0        NaN     77            NaN
2   103  Female   NaN     mumbai     13    maharashtra
3   104  Female  21.0        NaN     99            NaN
4   105    Male  23.0  Bengaluru     13      karnataka
5   106  Female  21.0        NaN     32            NaN
6   107    Male  23.0        NaN     13            NaN
7   108  Female  23.0        NaN     13            NaN
8   109     NaN  22.0        NaN     92            NaN
9   110    Male  23.0        NaN     10            NaN
10  111  Female   NaN      kochi     13         kerala
11  112  Female  21.0     mumbai     13    maharashtra
12  113  Female  21.0        NaN     65            NaN
13  114     NaN  21.0  Bengaluru     13      karnataka
14  115    Male  23.0        NaN     92            NaN
15  116    Male   NaN        NaN     77            NaN
16  117    Male  23.0  hyderabad     55  andra pradesh
17  118  Female  22.0    chennai     36     tamil nadu
18  119  Female   NaN      kochi     46         kerala
19  120  Female  23.0      kochi     46         kerala

# handle the null values of age and gender using fillna()

In [20]:
age_avg=df['age'].mean()

In [21]:
gen_mode=df['gender'].mode()[0]

In [22]:
df['age']=df['age'].fillna(age_avg)

In [23]:
df['gender']=df['gender'].fillna(gen_mode)

In [24]:
df

     id  gender      age   location  score          state
0   101  Female  22.0000  hyderabad     55  andra pradesh
1   102  Female  23.0000        NaN     77            NaN
2   103  Female  22.1875     mumbai     13    maharashtra
3   104  Female  21.0000        NaN     99            NaN
4   105    Male  23.0000  Bengaluru     13      karnataka
5   106  Female  21.0000        NaN     32            NaN
6   107    Male  23.0000        NaN     13            NaN
7   108  Female  23.0000        NaN     13            NaN
8   109  Female  22.0000        NaN     92            NaN
9   110    Male  23.0000        NaN     10            NaN
10  111  Female  22.1875      kochi     13         kerala
11  112  Female  21.0000     mumbai     13    maharashtra
12  113  Female  21.0000        NaN     65            NaN
13  114  Female  21.0000  Bengaluru     13      karnataka
14  115    Male  23.0000        NaN     92            NaN
15  116    Male  22.1875        NaN     77            NaN
16  117    Male  23.0000  hyderabad     55  andra pradesh
17  118  Female  22.0000    chennai     36     tamil nadu
18  119  Female  22.1875      kochi     46         kerala
19  120  Female  23.0000      kochi     46         kerala

# convert age column to intype usin astype()

In [25]:
df=df.astype({'age':'int'})

In [26]:
df

     id  gender  age   location  score          state
0   101  Female   22  hyderabad     55  andra pradesh
1   102  Female   23        NaN     77            NaN
2   103  Female   22     mumbai     13    maharashtra
3   104  Female   21        NaN     99            NaN
4   105    Male   23  Bengaluru     13      karnataka
5   106  Female   21        NaN     32            NaN
6   107    Male   23        NaN     13            NaN
7   108  Female   23        NaN     13            NaN
8   109  Female   22        NaN     92            NaN
9   110    Male   23        NaN     10            NaN
10  111  Female   22      kochi     13         kerala
11  112  Female   21     mumbai     13    maharashtra
12  113  Female   21        NaN     65            NaN
13  114  Female   21  Bengaluru     13      karnataka
14  115    Male   23        NaN     92            NaN
15  116    Male   22        NaN     77            NaN
16  117    Male   23  hyderabad     55  andra pradesh
17  118  Female   22    chennai     36     tamil nadu
18  119  Female   22      kochi     46         kerala
19  120  Female   23      kochi     46         kerala

# remove the column location,state bcz it has more null values (use dropna() )

In [30]:
df=df.dropna(axis=1).reset_index(drop=True)

# create the Result Classifications(grade) using score
(fail,first class,second class and distinction)

In [ ]:
df['score_category']=pd.cut(df['score'],bins=[1,30,40,60,85],labels=['fail','first class','second class','distinction'],include_lowest=True)

In [ ]:
df

     id  gender  age  score score_category
0   101  Female   22     55   second class
1   102  Female   23     77    distinction
2   103  Female   22     13           fail
3   104  Female   21     99            NaN
4   105    Male   23     13           fail
5   106  Female   21     32    first class
6   107    Male   23     13           fail
7   108  Female   23     13           fail
8   109  Female   22     92            NaN
9   110    Male   23     10           fail
10  111  Female   22     13           fail
11  112  Female   21     13           fail
12  113  Female   21     65    distinction
13  114  Female   21     13           fail
14  115    Male   23     92            NaN
15  116    Male   22     77    distinction
16  117    Male   23     55   second class
17  118  Female   22     36    first class
18  119  Female   22     46   second class
19  120  Female   23     46   second class

# get the no_of_students (using shape attribute)

In [ ]:
df.shape

(20, 5)

# get the gender wise no_of_studs (using value_counts() )

In [ ]:
df['gender'].value_counts()

gender
Female    14
Male       6
Name: count, dtype: int64

# find the average age

In [ ]:
df['age']=df['age'].fillna(age_avg)

# find the male average age

In [ ]:
df.loc[df['gender']=='Male'].agg({"age":["mean"]})

            age
mean  22.833333

# get the highest and lowest score

In [ ]:
df.agg({"score":["max","min"]})

     score
max     99
min     10

# get the gender wise highest  , lowest and average score

In [ ]:
df.groupby("gender").agg({"score":["max","min","mean"]})

       score
         max min       mean
gender
Female    99  13  43.785714
Male      92  10  43.333333